spring:
  profiles:
    active: local
  application:
    name: dev
  
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 0
      timeout: 2000ms

  cache:
    type: redis

  docker:
    compose:
      enabled: false

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1019073291684-f8q7dlkj8od60eeqpn1t94027pdlnmbv.apps.googleusercontent.com
            client-secret: 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
            scope: email, profile
            redirect-uri: http://localhost:8090/login/oauth2/code/google
            authorization-grant-type: authorization_code
        provider:
          google:
            user-name-attribute: email

  mail:
    host: smtp-relay.brevo.com
    port: 2525
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    protocol: smtp
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: "*"
        connectiontimeout: 10000
        timeout: 10000
        writetimeout: 10000

  jpa:
    hibernate:
      ddl-auto: update

cors:
  allowed-origins: http://localhost:3001,http://localhost:3000

server:
  port: 8090

jwt:
  secret: mySuperSecretKey123456789012345678901234567890
  access-expiration: 3600000
  refresh-expiration: 2592000000

recaptcha:
  secret: ${RECAPTCHA_SECRET}
  verify-url: https://www.google.com/recaptcha/api/siteverify
  threshold: 0.5